### ISSUE TITLE
wrong message of new version

### ISSUE THREAD

**Issue by ccoulet** [PANOimagen/batch_hillshader#1]
Hi
You have a problem in your version numbering (between metadata.txt and the zip version on the qgis plugin site) which leads to a permanent information of a new version of the plugin.
It could be great to solve this small bugs
Regards

**Comment by RobertoPanoi** [comment]
Thanks for the bug report. I have observed that in the official repository of QGIS, the version number is 2.1.90 and in the file metadata 2.01.90. Is that what you mean?

**Comment by ccoulet** [comment]
Yes
It could also be linked to the numbering of the zip file you upload on the Qgis plugin site...

**Comment by RobertoPanoi** [comment]
Is already solved, there was a problem with the management of the tags. I will update it shortly
