### ISSUE TITLE
TypeError: 'QVariant' object is not subscriptable 

### ISSUE THREAD

**Issue by ghost** [PANOimagen/batch_hillshader#4]
Hej,

I am trying to install plugin into qGIS 3.6.0. on windows 7, but I am receiving this error. Any help?

Couldn't load plugin 'batch_hillshader-master' due to an error when calling its classFactory() method 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/manuel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_hillshader-master\__init__.py", line 48, in classFactory
    return batchHillshader(iface)
  File "C:/Users/manuel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\batch_hillshader-master\batch_hillshader.py", line 68, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.0-Noosa Noosa, 58734527ab 

Python Path:
C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python
C:/Users/manuel/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/manuel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.6\bin\python37.zip
C:\PROGRA~1\QGIS3~1.6\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib
C:\Program Files\QGIS 3.6\bin
C:\PROGRA~1\QGIS3~1.6\apps\Python37
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\Pythonwin
C:/Users/manuel/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\manuel\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\manuel\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

**Comment by RobertoPanoi** [comment]
Hi @MarkoMarulic , could you try to launch the follow line code in the QGIS Python console and print the result of locale?
> `locale = QSettings().value('locale/userLocale')[0:2]`
> `print(locale)`

There are other QGIS plugins with the same problem, some solve it by deleting the plugin folder and trying to reinstall, I send the link of one of them: https://github.com/ghtmtt/DataPlotly/issues/78

Thanks

**Comment by ghost** [comment]
Hej Robert,

Looks like problem solved by it self :-) Today I started PC and plug in is working. Looks like restart help.

**Comment by RobertoPanoi** [comment]
Ok. We will look at what happened so that the error does not repeat itself. 
Thank you
