### ISSUE TITLE
FUSION and LASTools folders not found

### ISSUE THREAD

**Issue by Saijin-Naib** [PANOimagen/batch_hillshader#6]
![image](https://user-images.githubusercontent.com/19295950/69174451-dc5fdf00-0acf-11ea-9718-65a37a4ffc3e.png)

Batch Hillshader does not find these folders, though the path to them are set within my QGIS Processing Providers Settings.
![image](https://user-images.githubusercontent.com/19295950/69174516-fbf70780-0acf-11ea-984c-e97658c25e5c.png)

**Comment by RobertoPanoi** [comment]
The plugin has been updated to a new version (2.4.0) that does not depend on external dependencies with non-GPL licenses (LASTools and FUSION).

With previous versions (QGIS <3.0 and BH <2.4.0) the process with LASTools and FUSION is still available.

Thank you very much and sorry for the inconvenience
