### ISSUE TITLE
Upgrade for QGIS 3

### ISSUE THREAD

**Issue by foobarbecue** [PANOimagen/batch_hillshader#8]
Is this supposed to work on QGIS 3.x.x? I get `Plugin "batch_hillshader-master" is not compatible with this version of QGIS. It will be disabled."` on 3.10.0 .

**Comment by RobertoPanoi** [comment]
Which version of "batch hillshader" are you using?

**Comment by foobarbecue** [comment]
Sorry about this, it works fine on 3.10.0 . The actual problem is that I thought I didn't need laspy because I wasn't using .las . The real fix here is to make it clear in the documentation that laspy is always required.

**Comment by foobarbecue** [comment]
However, I did get that error message in my logs, when I tried to install it on 3.10.0 without laspy... I was installing the version from the qgis package repos, which was 2.4.0 .

**Comment by JaviBecerra** [comment]
Hi @foobarbecue,

I know this was posted long ago, this was fixed in version 2.4.1, plugin also works without laspy atm.

Regards,
Javier
